### Get product variants
POST http://localhost:3000/api/getProductVariants
Content-Type: application/json

{
  "ProductCategoryID": 1
}

### Place Order
POST http://localhost:3000/api/placeOrder
Content-Type: application/json

{
  "userid": 16,
  "cartId": 20,
  "DeliveryType": "delivery",
  "PaymentMethod": "COD",
  "AddressID": 1
}

### Drop Order
POST http://localhost:3000/api/dropOrders
Content-Type: application/json

{
  "orderId": 4
}
### Get Orders
POST http://localhost:3000/api/getOrders
Content-Type: application/json

{
  "userId": 1
}
### Get Product Attribute
POST http://localhost:3000/api/getAttribute
Content-Type: application/json

{
  "VariantID": 1
}

### Get Product Variants
POST http://localhost:3000/api/getProductVariants
Content-Type: application/json

{
  "ProductID": 1
}

### Get Variant
POST http://localhost:3000/api/UnRegCart
Content-Type: application/json

{
  "VariantID": 1
}


### Set Cart Item
POST http://localhost:3000/api/unRegSetCart
Content-Type: application/json

{
  "VariantID": 1,
  "cartId": 1,
  "quantity": 2
}

### Add Address
POST http://localhost:3000/api/addAddress
Content-Type: application/json

{
  "AddressNumber": 4,
  "Lane": "Main Street",
  "City": "Metropolis",
  "PostalCode": "12345",
  "District": "Anuradhpura"
}

### Add User and Get Cart ID
POST http://localhost:3000/api/addUnregCustomer
Content-Type: application/json

{
  "PhoneNumber": "1234567890",
  "FirstName": "John",
  "LastName": "Doe",
  "Role": "Registered"
}

### Get User Cart ID
POST http://localhost:3000/api/getUserCartId
Content-Type: application/json

{
  "userId": 16
}

### Get User Info
POST http://localhost:3000/api/getUserInfo
Content-Type: application/json

{
  "userId": 16
}